import ig_account

IDLE_FOR_PER_ACCOUNT = 5
CONSTANT_IDLE_RANDOM_MULTIPILER_FOR_PER_ACCOUNT = 1
IDLE_FOR_PER_ITERATE = 300
CONSTANT_IDLE_RANDOM_MULTIPILER_FOR_PER_ITERATE = 10
IDLE_FOR_UNHANDLED_BAN = 600
IDLE_FOR_ELEMENT_TO_BE_FOUND = 10

TEST_ACCOUNTS = [ 
    ig_account.IG_ACCOUNT("username", "password")
]

ACCOUNTS = ["cristiano", "arianagrande"]